import type { ChapterDefinition } from "@/lib/types";

export const CHAPTERS: ChapterDefinition[] = [

  // ─── Fase 1: Wie ben jij? ────────────────────────────────────────────────
  {
    id: "intro-reflection",
    phase: "intro",
    phaseTitle: "Fase 1: Wie ben jij?",
    title: "Kernwoorden van je leven",
    description: "Beschrijf je leven in één alinea",
    question: "Als je jouw leven tot nu toe zou moeten beschrijven in één alinea, welke kernwoorden en gevoelens zouden daarin dan centraal staan?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - nodigt uit tot reflectie en samenvatting",
  },
  {
    id: "intro-intention",
    phase: "intro",
    phaseTitle: "Fase 1: Wie ben jij?",
    title: "Je intentie",
    description: "Waarom leg je dit vast?",
    question: "Waarom ben je begonnen aan dit project om jouw levensverhaal vast te leggen? Wat hoop je hiermee te bereiken, of voor wie doe je het?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - opname van de intentie, direct uit het hart",
  },
  {
    id: "intro-uniqueness",
    phase: "intro",
    phaseTitle: "Fase 1: Wie ben jij?",
    title: "Wat maakt jou uniek",
    description: "Drie dingen die jou definiëren",
    question: "Beschrijf drie dingen die jou uniek maken en die je absoluut in je levensverhaal wilt opnemen.",
    mood: "celebratory",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - vastleggen van belangrijke facetten",
  },

  // ─── Fase 2: Je Wortels ──────────────────────────────────────────────────
  {
    id: "roots-first-memory",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Je vroegste herinnering",
    description: "Het allereerste wat je je herinnert",
    question: "Wat is het vroegste dat jij je herinnert — een beeld, een gevoel, een geur? Hoe oud was je, en wat was er om je heen?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - stemkwaliteit brengt de kwetsbaarheid van vroege herinneringen tot leven",
  },
  {
    id: "roots-father",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Je vader",
    description: "Wie was hij als mens?",
    question: "Vertel over je vader — wie was hij als mens, niet alleen als vader? Wat voor werk deed hij, waar lachte hij om, en hoe was hij voor jou?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - persoonlijk verhaal met ruimte voor nuance en emotie",
  },
  {
    id: "roots-mother",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Je moeder",
    description: "Wie was zij als mens?",
    question: "Vertel over je moeder. Wat maakte haar bijzonder? Hoe rook ze, hoe klonk haar stem, en wat zijn de dingen die je nooit zult vergeten?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - zintuiglijke details komen het best tot hun recht in gesproken woord",
  },
  {
    id: "roots-grandparents",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Je grootouders",
    description: "De generatie vóór je ouders",
    question: "Wat weet je over je grootouders — wie waren ze, waar kwamen ze vandaan, en wat hebben ze doorgegeven aan jouw familie?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - uitgebreid verhaal met namen, plaatsen en details voor het familiegeheugen",
  },
  {
    id: "roots-siblings",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Broers, zussen en het gezinsleven",
    description: "Hoe was de sfeer thuis?",
    question: "Hoe was het gezin thuis — had je broers of zussen, en hoe was de sfeer aan tafel, op vrije zaterdagen, of tijdens de vakanties?",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - anekdotes en humor komen goed tot hun recht via stem",
  },
  {
    id: "roots-home",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Het ouderlijk huis",
    description: "Beschrijf het huis waar je opgroeide",
    question: "Beschrijf het huis waar je opgroeide — welke kamer herinner je je het best, wat hing er aan de muren, en welke geuren horen daarbij?",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - eventueel oude foto's tonen van het huis of de buurt",
  },
  {
    id: "roots-neighborhood",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Je buurt of dorp",
    description: "Hoe was de plek waar je opgroeide?",
    question: "Hoe was de buurt of het dorp waar je opgroeide — wat speelde er buiten, wie waren de buren, en wat was het dagelijkse leven daar?",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - levendig vertellen over de buitenwereld van je jeugd",
  },
  {
    id: "roots-faith",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Geloof en levensbeschouwing",
    description: "Welke rol speelde religie of levensbeschouwing?",
    question: "Welke rol speelde geloof of levensbeschouwing in je gezin, en wat betekende dat voor jouw opvoeding en hoe je de wereld leerde zien?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - nuancerede reflectie op een persoonlijk onderwerp",
  },
  {
    id: "roots-finances",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Het financiële klimaat thuis",
    description: "Had je het krap of ruim als kind?",
    question: "Hoe was het financieel in het gezin waar je opgroeide — had je het krap of ruim, en hoe merkte je dat als kind in het dagelijkse leven?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - persoonlijk en eerlijk verhaal over klassenachtergrond",
  },
  {
    id: "roots-hardship",
    phase: "roots",
    phaseTitle: "Fase 2: Je Wortels",
    title: "Wat je meedroeg",
    description: "Iets moeilijks uit je vroege jeugd",
    question: "Was er iets moeilijks in je vroege jeugd — iets in je gezin, iets wat je meemaakte — dat je hebt meegedragen? Je hoeft alleen te vertellen wat je wilt.",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - ruimte voor kwetsbaarheid en eigen tempo",
  },

  // ─── Fase 3: Jeugd & School ──────────────────────────────────────────────
  {
    id: "youth-favorite-place",
    phase: "youth",
    phaseTitle: "Fase 3: Jeugd & School",
    title: "Je favoriete plek",
    description: "Een plek uit je kindertijd",
    question: "Neem ons mee naar je favoriete plek uit je kindertijd. Beschrijf wat je daar zag, hoorde, rook en voelde. Als je zou kunnen, welk moment zou je daar dan opnieuw beleven?",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - visuele weergave van nostalgie",
  },
  {
    id: "youth-sounds",
    phase: "youth",
    phaseTitle: "Fase 3: Jeugd & School",
    title: "Het geluid van toen",
    description: "Een geluid uit je jeugd",
    question: "Welk geluid associeer je het meest met je jeugd? Vertel een korte anekdote die bij dit geluid hoort en waarom het zo belangrijk voor je is.",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - focus op zintuiglijke herinneringen",
  },
  {
    id: "youth-hero",
    phase: "youth",
    phaseTitle: "Fase 3: Jeugd & School",
    title: "Je held",
    description: "Je rolmodel uit je jeugd",
    question: "Wie was jouw grootste held of rolmodel toen je jong was, en welke invloed heeft die persoon gehad op wie je nu bent?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - reflectie op vormende invloeden",
  },
  {
    id: "youth-primary-school",
    phase: "youth",
    phaseTitle: "Fase 3: Jeugd & School",
    title: "De lagere school",
    description: "Een leraar die je nooit vergat",
    question: "Welke leraar of juf van de lagere school herinner je je nog, en wat maakte hem of haar zo bijzonder dat je hen nooit vergat?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - persoonlijke anekdote over een vormer",
  },
  {
    id: "youth-friends",
    phase: "youth",
    phaseTitle: "Fase 3: Jeugd & School",
    title: "Je vrienden",
    description: "Je beste vriend of vriendin als kind",
    question: "Wie was je beste vriend of vriendin als kind of tiener, en wat deden jullie samen dat jou het gelukkigst maakte?",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - vrolijke herinneringen aan vriendschap",
  },
  {
    id: "youth-secondary-school",
    phase: "youth",
    phaseTitle: "Fase 3: Jeugd & School",
    title: "De middelbare school",
    description: "Hoe was jij als tiener?",
    question: "Hoe was de middelbare school voor jou — wat vond je het leukst, wat vond je het moeilijkst, en wat herinner je je van wie je toen was?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - zelfreflectie op de tienerjaren",
  },
  {
    id: "youth-history",
    phase: "youth",
    phaseTitle: "Fase 3: Jeugd & School",
    title: "De tijdgeest van jouw jeugd",
    description: "Nederland zoals jij het beleefde",
    question: "Wat speelde er in Nederland — of de wereld — toen jij opgroeide, en hoe merkte je dat thuis, op straat, of op school?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - persoonlijke beleving van historische context",
  },
  {
    id: "youth-ambition",
    phase: "youth",
    phaseTitle: "Fase 3: Jeugd & School",
    title: "Wat je wilde worden",
    description: "Dromen als tiener",
    question: "Wat droomde je ervan te worden toen je een tiener was, en wat dacht je op dat moment écht dat je zou gaan doen met je leven?",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - luchtige reflectie op jeugdige ambitie",
  },

  // ─── Fase 4: Jong Volwassen ──────────────────────────────────────────────
  {
    id: "work-dream-job",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "Droom versus realiteit",
    description: "Je droombaan als kind",
    question: "Wat was je droombaan als kind en hoe verhoudt zich dat tot wat je uiteindelijk bent gaan doen? Wat heb je meegenomen van die kinderdroom?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - vergelijking droom en realiteit",
  },
  {
    id: "work-passion",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "Je grootste passie",
    description: "Wat boeit je het meest?",
    question: "Laat ons iets zien (een project, een hobby, een instrument, een boek) dat jouw grootste passie buiten werk vertegenwoordigt. Vertel waarom dit je zo boeit en wat het je brengt.",
    mood: "celebratory",
    defaultModalities: ["video"],
    mediaFocus: "Video - visualiseer passie en enthousiasme",
  },
  {
    id: "work-challenge",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "Een overwonnen uitdaging",
    description: "Een professionele mijlpaal",
    question: "Beschrijf een moment waarop je een grote professionele uitdaging hebt overwonnen. Wat was die uitdaging en welke impact had het op je?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - stemgebruik voor spanning en triomf",
  },
  {
    id: "young-adult-first-job",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "Je eerste baan",
    description: "Het begin van je werkende leven",
    question: "Wat was je eerste echte baan, hoe oud was je, wat verdiende je, en hoe was het om voor het eerst je eigen geld te verdienen?",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - levendig verhaal over de eerste stappen in het werkende leven",
  },
  {
    id: "young-adult-independence",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "Zelfstandig worden",
    description: "De eerste stappen op eigen benen",
    question: "Hoe was het toen je voor het eerst echt op jezelf was — was je opgewonden, bang, of allebei, en wat was de grootste verrassing?",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - emotioneel en energiek verhaal over zelfstandigheid",
  },
  {
    id: "young-adult-first-home",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "Je eerste eigen plek",
    description: "De eerste kamer of het eerste huis",
    question: "Beschrijf de eerste kamer of het eerste huis dat van jou was — hoe zag het eruit, wat kookte je, en hoe voelde dat?",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - eventueel oude foto's van het eerste huis",
  },
  {
    id: "young-adult-career-path",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "Hoe je loopbaan zich ontvouwde",
    description: "Het traject van je werkzame leven",
    question: "Hoe heeft je werk zich door de jaren heen ontwikkeld — was er een moment waarop alles een andere richting inging, en wat bracht dat teweeg?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - chronologisch verhaal van loopbaantraject",
  },
  {
    id: "young-adult-pivotal-choice",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "De keuze die alles veranderde",
    description: "Een beslissing die je leven vormde",
    question: "Welke beslissing in je twintiger of dertiger jaren heeft jouw leven het sterkst gevormd — en was dat op dat moment al duidelijk, of pas later?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - reflectieve terugblik op een bepalend moment",
  },
  {
    id: "young-adult-finances",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "Jouw relatie met geld",
    description: "Hoe was het financieel als jonge volwassene?",
    question: "Hoe was het financieel toen je jong volwassen was — had je het krap, hoe ging je daarmee om, en wat leerde je over geld in die jaren?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - eerlijk en nuanceerd verhaal over geld en zekerheid",
  },
  {
    id: "young-adult-world-events",
    phase: "young-adult",
    phaseTitle: "Fase 4: Jong Volwassen",
    title: "De wereld toen je jong volwassen was",
    description: "Een wereldgebeurtenis die jou raakte",
    question: "Welke grote gebeurtenis in Nederland of de wereld raakte jou het meest in je twintig of dertig jaar, en hoe kijk je daar nu op terug?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - persoonlijke beleving van historische momenten",
  },

  // ─── Fase 5: Liefde & Gezin ──────────────────────────────────────────────
  {
    id: "love-connection",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "Het moment van verbinding",
    description: "Toen je wist dat het bijzonder was",
    question: "Beschrijf het moment waarop je wist dat je verliefd was, of een heel speciale connectie voelde met iemand. Wat maakte dat gevoel zo uniek?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - klemtoon op intonatie en emotie in stem",
  },
  {
    id: "love-lessons",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "Lessen over liefde",
    description: "Wijsheid die je wilt doorgeven",
    question: "Welke drie lessen heb je geleerd over liefde of vriendschap die je zou willen doorgeven aan toekomstige generaties?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - gecondenseerde wijsheid",
  },
  {
    id: "love-symbol",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "Een symbolisch voorwerp",
    description: "Voorwerp dat een relatie vertegenwoordigt",
    question: "Kies een voorwerp dat symbool staat voor een belangrijke relatie of vriendschap in je leven. Laat het zien en vertel het verhaal erachter.",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - visuele trigger voor een persoonlijk verhaal",
  },
  {
    id: "family-partner-story",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "Hoe jullie verhaal begon",
    description: "Het hele verhaal van hoe jullie elkaar leerden kennen",
    question: "Vertel het hele verhaal van hoe jij en je partner elkaar leerden kennen — de omstandigheden, de eerste indruk, en wanneer je wist dat dit anders was.",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - romantisch en levendig verhaal",
  },
  {
    id: "family-early-years",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "De eerste jaren samen",
    description: "Hoogte- en dieptepunten van het begin",
    question: "Hoe waren de eerste jaren van jullie relatie of huwelijk — wat waren de hoogtepunten, wat waren de moeilijkheden, en hoe groeide jullie band?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - eerlijk en warm verhaal over samen beginnen",
  },
  {
    id: "family-wedding",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "De trouwdag of het beginpunt",
    description: "Wat herinner je je van die dag?",
    question: "Vertel over de dag dat jullie trouwden of het moment dat jullie besloten echt samen te gaan — wat herinner je je het meest van die dag?",
    mood: "celebratory",
    defaultModalities: ["video"],
    mediaFocus: "Video - eventueel trouwfoto's tonen en er verhalen bij vertellen",
  },
  {
    id: "family-children",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "Het ouderschap",
    description: "Kinderen krijgen en opvoeden",
    question: "Had je kinderen — en als je nu terugkijkt op die jaren, wat herinner je je het best, wat was het moeilijkst, en waar ben je het meest trots op?",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - foto's van de kinderen als kapstok voor verhalen",
  },
  {
    id: "family-typical-week",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "Een gewone week met kinderen",
    description: "Het dagelijkse leven als gezin",
    question: "Beschrijf hoe een gewone week eruitzag toen je kinderen nog thuis woonden — wie deed wat, hoe waren de maaltijden, en wat mis je daar nu van?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - rijke details van het dagelijkse gezinsleven",
  },
  {
    id: "family-hardship",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "Moeilijke tijden als gezin",
    description: "Hoe jullie samen door moeilijkheden gingen",
    question: "Heeft je gezin ooit een moeilijke periode doorgemaakt — verlies, ziekte, conflict, of een andere beproeving — en hoe hebben jullie dat samen doorstaan?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - kwetsbaar verhaal, eigen tempo respecteren",
  },
  {
    id: "family-pride",
    phase: "family",
    phaseTitle: "Fase 5: Liefde & Gezin",
    title: "Waar je het meest trots op bent",
    description: "De trots van een gezinsleven",
    question: "Als je kijkt naar je gezin of je relaties — wat maakt je het meest trots, en wat wil je dat je kinderen of kleinkinderen hierover weten?",
    mood: "celebratory",
    defaultModalities: ["video"],
    mediaFocus: "Video - directe boodschap aan de volgende generatie",
  },

  // ─── Fase 6: Midden Leven & Verlies ─────────────────────────────────────
  {
    id: "midlife-grief",
    phase: "midlife",
    phaseTitle: "Fase 6: Midden Leven & Verlies",
    title: "Het verlies dat je draagt",
    description: "Iemand wiens afwezigheid je nog voelt",
    question: "Is er iemand die je hebt verloren — een ouder, een vriend, een geliefde — wiens afwezigheid je nog steeds voelt? Vertel over hen als je dat wilt.",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - ruimte voor stiltes en emotie",
  },
  {
    id: "midlife-aging",
    phase: "midlife",
    phaseTitle: "Fase 6: Midden Leven & Verlies",
    title: "Ouder worden",
    description: "Wanneer merkte je het écht?",
    question: "Op welk moment merkte je voor het eerst dat je ouder werd — niet als een getal, maar echt, in je lijf of je kijk op het leven?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - intieme reflectie op het lichaam en de tijd",
  },
  {
    id: "midlife-regret",
    phase: "midlife",
    phaseTitle: "Fase 6: Midden Leven & Verlies",
    title: "Wat je anders zou doen",
    description: "Eerlijk terugkijken op gemiste kansen",
    question: "Is er iets in je leven dat anders is gegaan dan je had gehoopt — iets wat je zou willen veranderen, als je eerlijk naar jezelf kijkt?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - ruimte voor eerlijke zelfreflectie zonder tijdsdruk",
  },
  {
    id: "midlife-resilience",
    phase: "midlife",
    phaseTitle: "Fase 6: Midden Leven & Verlies",
    title: "Wat je leerde van tegenslag",
    description: "Hoe moeilijkheid je vormde",
    question: "Wat heeft het leven je geleerd over tegenslagen — is er een moeilijke periode waarvan je nu zegt: zonder dat was ik een ander mens geweest?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - krachtig verhaal over veerkracht",
  },
  {
    id: "midlife-parents-retrospect",
    phase: "midlife",
    phaseTitle: "Fase 6: Midden Leven & Verlies",
    title: "Je ouders nu je ouder bent",
    description: "Terugkijken op je ouders met andere ogen",
    question: "Hoe kijk je nu op je ouders terug, nu je zelf ouder bent — begrijp je dingen die je vroeger niet begreep, en wat zou je ze willen zeggen?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - diep en persoonlijk verhaal over begrip en vergeving",
  },
  {
    id: "midlife-formative-decade",
    phase: "midlife",
    phaseTitle: "Fase 6: Midden Leven & Verlies",
    title: "Je rijkste decennium",
    description: "Welke tien jaar waren het meest bepalend?",
    question: "Welk decennium van je leven — de jaren '60, '70, '80, of later — was voor jou het rijkst of het meest bepalend, en waarom dat tijdvak?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - historisch en persoonlijk portret van een tijdvak",
  },
  {
    id: "midlife-social-change",
    phase: "midlife",
    phaseTitle: "Fase 6: Midden Leven & Verlies",
    title: "Hoe Nederland veranderde rond jou",
    description: "Maatschappelijke veranderingen die jou raakten",
    question: "Welke grote maatschappelijke verandering in Nederland heeft jouw leven direct geraakt — denk aan de ontzuiling, de vrouwenbeweging, de opkomst van de computer — en hoe?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - persoonlijke beleving van bredere maatschappelijke verschuivingen",
  },
  {
    id: "midlife-faith-evolution",
    phase: "midlife",
    phaseTitle: "Fase 6: Midden Leven & Verlies",
    title: "Hoe je kijk op het leven veranderde",
    description: "Wijsheid die alleen de tijd brengt",
    question: "Hoe is je kijk op het leven, op geluk, of op wat echt telt veranderd tussen jouw twintiger jaren en nu — wat weet je nu dat je toen niet wist?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - rijpe wijsheid over het leven",
  },

  // ─── Fase 7: Nu & Nalatenschap ───────────────────────────────────────────
  {
    id: "future-message",
    phase: "legacy",
    phaseTitle: "Fase 7: Nu & Nalatenschap",
    title: "Een boodschap voor later",
    description: "Wat wil je meegeven?",
    question: "Als je één boodschap of levensles zou mogen meegeven aan jezelf van 20 jaar geleden, of aan je nakomelingen, wat zou dat dan zijn en waarom?",
    mood: "reflective",
    defaultModalities: ["video"],
    mediaFocus: "Video - directe, persoonlijke boodschap met oogcontact",
  },
  {
    id: "future-dream",
    phase: "legacy",
    phaseTitle: "Fase 7: Nu & Nalatenschap",
    title: "Een onvervulde droom",
    description: "Wat koester je nog steeds?",
    question: "Welke droom of aspiratie koester je nog steeds, ongeacht leeftijd of omstandigheden? Wat maakt deze droom zo krachtig voor je?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - vastleggen van onvervulde verlangens of blijvende hoop",
  },
  {
    id: "future-gratitude",
    phase: "legacy",
    phaseTitle: "Fase 7: Nu & Nalatenschap",
    title: "Dankbaarheid",
    description: "Waar ben je dankbaar voor?",
    question: "Beschrijf drie dingen waar je het meest dankbaar voor bent in je leven. Waarom zijn deze zo belangrijk voor je?",
    mood: "gentle",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - focus op dankbaarheid en positieve afsluiting",
  },
  {
    id: "legacy-daily-joy",
    phase: "legacy",
    phaseTitle: "Fase 7: Nu & Nalatenschap",
    title: "Wat jou nu vreugde geeft",
    description: "Geluk in het gewone",
    question: "Hoe is je leven nu — wat brengt je vreugde op een gewone dag, en wat heb je geleerd over wat gelukkig zijn werkelijk betekent?",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - toon wat er nu is, niet alleen wat er was",
  },
  {
    id: "legacy-faith-now",
    phase: "legacy",
    phaseTitle: "Fase 7: Nu & Nalatenschap",
    title: "Geloof en zingeving vandaag",
    description: "Hoe jij nu betekenis vindt",
    question: "Wat betekent geloof, spiritualiteit, of zingeving voor je op dit punt in je leven — is dat veranderd ten opzichte van hoe je opgroeide?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - persoonlijke en intieme reflectie op zingeving",
  },
  {
    id: "legacy-remembered",
    phase: "legacy",
    phaseTitle: "Fase 7: Nu & Nalatenschap",
    title: "Hoe je herinnerd wilt worden",
    description: "Je eigen definitie van je leven",
    question: "Als je terugdenkt aan alles wat je hebt meegemaakt — hoe wil je herinnerd worden? Wat is de ene zin die jou het beste samenvat?",
    mood: "reflective",
    defaultModalities: ["video"],
    mediaFocus: "Video - directe blik in de camera, de zin die blijft",
  },
  {
    id: "legacy-verdict",
    phase: "legacy",
    phaseTitle: "Fase 7: Nu & Nalatenschap",
    title: "Je oordeel over je eigen leven",
    description: "Was dit het leven dat je wilde leiden?",
    question: "Als je eerlijk terugkijkt: was dit het leven dat je wilde leiden? En als je dat vraagt aan jezelf, wat antwoord je dan?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - het meest eerlijke en persoonlijke moment in het hele traject",
  },
  {
    id: "legacy-unsaid",
    phase: "legacy",
    phaseTitle: "Fase 7: Nu & Nalatenschap",
    title: "Wat je nooit hardop hebt gezegd",
    description: "Nu de kans om het te zeggen",
    question: "Is er iets wat je nooit hardop hebt gezegd — een gevoel, een dankbaarheid, een verontschuldiging — dat je hier en nu wilt uitspreken?",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - rechtstreeks naar de kijker, als een echte brief",
  },
  {
    id: "legacy-letter",
    phase: "legacy",
    phaseTitle: "Fase 7: Nu & Nalatenschap",
    title: "Een brief aan de volgende generatie",
    description: "Wat jij wil dat zij weten",
    question: "Als je één brief mocht schrijven of inspreken aan je kleinkinderen of de generaties na jou — wat zou je daarin zeggen?",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - persoonlijke video-brief, het meest waardevolle dat achterblijft",
  },

  // ─── Optioneel: Verdieping & Creativiteit ────────────────────────────────
  {
    id: "bonus-funny",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Het grappigste moment",
    description: "Het meest onverwachte",
    question: "Wat is het grappigste of meest onverwachte moment in je leven geweest?",
    mood: "playful",
    defaultModalities: ["video", "audio", "text"],
    mediaFocus: "Vrije keuze",
  },
  {
    id: "bonus-relive",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Een dag opnieuw",
    description: "Welke dag zou je herbeleven?",
    question: "Als je één dag opnieuw zou kunnen beleven, welke dag zou dat zijn en waarom?",
    mood: "reflective",
    defaultModalities: ["video", "audio", "text"],
    mediaFocus: "Vrije keuze",
  },
  {
    id: "bonus-culture",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Culturele invloeden",
    description: "Kunst die je vormde",
    question: "Welke culturele invloed (muziek, kunst, boeken, film) heeft jou het meest gevormd?",
    mood: "celebratory",
    defaultModalities: ["video", "audio", "text"],
    mediaFocus: "Vrije keuze",
  },
  {
    id: "deep-daily-ritual",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Je essentiële ritueel",
    description: "Een dagelijks moment dat je niet wilt missen",
    question: "Welk alledaags ritueel (bijv. ochtendkoffie, de avondwandeling) zou je het meest missen als je het niet meer kon doen? Beschrijf de stappen en de exacte gemoedstoestand die dit ritueel je geeft.",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - gedetailleerde beschrijving van routines",
  },
  {
    id: "deep-favorite-time",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Je favoriete uur",
    description: "Het tijdstip van de dag dat je het meest waardeert",
    question: "Neem ons mee naar je favoriete tijdstip van de dag. Waarom is dit uur zo speciaal voor jou? Welk geluid, welke lichtval of welke stilte kenmerkt dit moment?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - zintuiglijke ervaring van tijd",
  },
  {
    id: "deep-ugly-object",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Het lelijke object",
    description: "Iets dat je niet weggooit ondanks alles",
    question: "Laat ons het 'lelijkste' object in je huis zien, dat je toch weigert weg te gooien. Waarom heeft dit object, dat niet mooi is, zo'n emotionele grip op je?",
    mood: "playful",
    defaultModalities: ["video"],
    mediaFocus: "Video - visuele weergave van het object",
  },
  {
    id: "deep-near-death",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Bijna-doodervaring of bizar toeval",
    description: "Een moment dat alles veranderde",
    question: "Vertel over een bijna-doodervaring of een heel bizar toeval dat je hebt meegemaakt. Wat dacht je in die milliseconden, en hoe heeft het je perspectief op het leven beïnvloed?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - emotionele lading en intonatie",
  },
  {
    id: "deep-misconception",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "De misvatting over jou",
    description: "Wat mensen verkeerd begrijpen",
    question: "Wat is de meest hardnekkige misvatting die mensen over jou hebben, of die je over jezelf hebt gehad? Hoe heb je deze misvatting doorbroken?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - reflectie op zelfbeeld",
  },
  {
    id: "deep-recurring-dream",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Je terugkerende droom",
    description: "Symbolen uit je droomwereld",
    question: "Beschrijf je typische droom (of nachtmerrie). Zijn er terugkerende symbolen of thema's? Hoe relateert deze droomwereld aan je wakkere leven?",
    mood: "reflective",
    defaultModalities: ["video"],
    mediaFocus: "Video - visuele beschrijving van droombeelden",
  },
  {
    id: "deep-life-chapters",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Hoofdstukken van je leven",
    description: "Je leven als een boek",
    question: "Als je jouw leven in hoofdstukken zou verdelen (zoals een boek), wat zouden de titel van Hoofdstuk 1 (Jeugd) en de titel van het huidige hoofdstuk zijn? Leg kort de titels uit.",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - metaforische reflectie op levensfasen",
  },
  {
    id: "deep-intuition-choice",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Intuïtie boven logica",
    description: "Een beslissing uit je buikgevoel",
    question: "Beschrijf een moment waarop je een beslissing nam, puur en alleen uit intuïtie, tegen alle logica of advies in. Wat was de uitkomst, en wat leerde je over je eigen innerlijke stem?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - persoonlijke reflectie op innerlijke wijsheid",
  },
  {
    id: "deep-money-impact",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "De meest impactvolle aankoop",
    description: "Wat geld je bracht",
    question: "Kies een willekeurig bedrag (bijv. 50 euro). Wat is de meest impactvolle of onvergetelijke aankoop die je ooit met dit bedrag (of een vergelijkbaar bedrag) hebt gedaan, en waarom?",
    mood: "reflective",
    defaultModalities: ["video"],
    mediaFocus: "Video - visualiseer de impact van keuzes",
  },
  {
    id: "deep-shadow-side",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Je schaduwzijde",
    description: "De kant die je minder waardeert",
    question: "Als je jouw eigen 'schaduwzijde' (de minst gewaardeerde karaktertrek) in drie woorden zou moeten beschrijven, welke zouden dat zijn? Hoe ga je daar vandaag de dag mee om?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - eerlijke zelfreflectie",
  },
  {
    id: "deep-life-meal",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "De maaltijd van je leven",
    description: "Een gerecht dat jou samenvat",
    question: "Als je één maaltijd zou moeten kiezen die jouw leven perfect samenvat (qua ingrediënten, smaken, of bereiding), welke zou dat zijn? Beschrijf het en vertel het verhaal erachter.",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - zintuiglijke metafoor voor het leven",
  },
  {
    id: "deep-statue",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Je eigen standbeeld",
    description: "Hoe zou jouw monument eruitzien?",
    question: "Stel je voor dat je jouw eigen standbeeld mag ontwerpen. Hoe zou het eruitzien, waar zou het staan, en welke drie woorden zouden op de sokkel staan? Geef je motivatie.",
    mood: "celebratory",
    defaultModalities: ["video"],
    mediaFocus: "Video - definitie van de zelfgekozen nalatenschap",
  },
  {
    id: "optional-childhood-game",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Spel van vroeger",
    description: "Een spel dat je nooit vergat",
    question: "Welk spel of tijdverdrijf uit je kindertijd zou je nu nog weleens willen doen, en wie speelde er altijd met je mee?",
    mood: "playful",
    defaultModalities: ["audio", "video", "text"],
    mediaFocus: "Vrije keuze",
  },
  {
    id: "optional-alter-ego",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Je alter ego",
    description: "Wie was je geworden met andere keuzes?",
    question: "Als je een heel ander leven had geleid — andere keuzes, ander land, andere tijd — wie denk je dan dat je geworden zou zijn?",
    mood: "playful",
    defaultModalities: ["audio", "text"],
    mediaFocus: "Vrije keuze",
  },
  {
    id: "optional-superpower",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Je bijzondere eigenschap",
    description: "De kracht die anderen niet zien",
    question: "Welke eigenschap van jezelf heeft je het meest geholpen in het leven — iets wat anderen misschien niet eens opmerken, maar wat jij voelt als een kracht?",
    mood: "celebratory",
    defaultModalities: ["audio", "text"],
    mediaFocus: "Vrije keuze",
  },
  {
    id: "optional-bucket-list",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Wat je nog wilt",
    description: "Het verlanglijstje voor de rest van je leven",
    question: "Wat staat er nog op je verlanglijst — iets wat je wilt doen, zien, zeggen, of meemaken — en wat weerhoudt je er nog van?",
    mood: "gentle",
    defaultModalities: ["audio", "text"],
    mediaFocus: "Vrije keuze",
  },
  {
    id: "optional-final-chapter",
    phase: "optional",
    phaseTitle: "Optioneel: Verdieping & Creativiteit",
    title: "Het laatste hoofdstuk schrijven",
    description: "Hoe wil je dat het verdergaat?",
    question: "Als je het laatste hoofdstuk van je leven mag schrijven — de jaren die nog komen — wat hoop je dat daarin staat?",
    mood: "gentle",
    defaultModalities: ["audio", "video"],
    mediaFocus: "Vrije keuze",
  },
];

// Helper functions
export function getChaptersByPhase(phase: ChapterDefinition["phase"]): ChapterDefinition[] {
  return CHAPTERS.filter((ch) => ch.phase === phase);
}

export function getPhases(): Array<{ id: ChapterDefinition["phase"]; title: string; description: string; chapterCount: number }> {
  const corePhases: Array<{ id: ChapterDefinition["phase"]; title: string; description: string }> = [
    {
      id: "intro",
      title: "Fase 1: Wie ben jij?",
      description: "Een eerste blik op wie je bent en waarom je dit verhaal vastlegt",
    },
    {
      id: "roots",
      title: "Fase 2: Je Wortels",
      description: "Je ouders, grootouders, gezin en de wereld waarin je werd geboren",
    },
    {
      id: "youth",
      title: "Fase 3: Jeugd & School",
      description: "De jaren van spelen, leren en worden wie je bent",
    },
    {
      id: "young-adult",
      title: "Fase 4: Jong Volwassen",
      description: "Je eerste baan, grote keuzes en het leven dat je zelf begon te bouwen",
    },
    {
      id: "family",
      title: "Fase 5: Liefde & Gezin",
      description: "Liefde, partnerschap, kinderen en de relaties die je leven kleur geven",
    },
    {
      id: "midlife",
      title: "Fase 6: Midden Leven & Verlies",
      description: "Tegenslagen, verlies, veerkracht en de wijsheid die de tijd brengt",
    },
    {
      id: "legacy",
      title: "Fase 7: Nu & Nalatenschap",
      description: "Wie je nu bent, wat je hebt geleerd en wat je wilt achterlaten",
    },
    {
      id: "optional",
      title: "Optioneel: Verdieping & Creativiteit",
      description: "Extra vragen voor wie nog meer wil vertellen",
    },
  ];

  return corePhases.map((p) => ({
    ...p,
    chapterCount: getChaptersByPhase(p.id).length,
  }));
}

export function getCoreChapters(): ChapterDefinition[] {
  return CHAPTERS.filter((ch) => ch.phase !== "optional");
}
