import type { ChapterDefinition } from "@/lib/types";

export const CHAPTERS: ChapterDefinition[] = [
  // Fase 1: Voorbereiding & Introductie
  {
    id: "intro-reflection",
    phase: "intro",
    phaseTitle: "Fase 1: Voorbereiding & Introductie",
    title: "Kernwoorden van je leven",
    description: "Beschrijf je leven in één alinea",
    question: "Als je jouw leven tot nu toe zou moeten beschrijven in één alinea, welke kernwoorden en gevoelens zouden daarin dan centraal staan?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - nodigt uit tot reflectie en samenvatting",
  },
  {
    id: "intro-intention",
    phase: "intro",
    phaseTitle: "Fase 1: Voorbereiding & Introductie",
    title: "Je intentie",
    description: "Waarom leg je dit vast?",
    question: "Waarom ben je begonnen aan dit project om jouw levensverhaal vast te leggen? Wat hoop je hiermee te bereiken, of voor wie doe je het?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - opname van de intentie, direct uit het hart",
  },
  {
    id: "intro-uniqueness",
    phase: "intro",
    phaseTitle: "Fase 1: Voorbereiding & Introductie",
    title: "Wat maakt jou uniek",
    description: "Drie dingen die jou definiëren",
    question: "Beschrijf drie dingen die jou uniek maken en die je absoluut in je levensverhaal wilt opnemen.",
    mood: "celebratory",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - vastleggen van belangrijke facetten",
  },

  // Fase 2: De Vroege Jaren & Jeugd
  {
    id: "youth-favorite-place",
    phase: "youth",
    phaseTitle: "Fase 2: De Vroege Jaren & Jeugd",
    title: "Je favoriete plek",
    description: "Een plek uit je kindertijd",
    question: "Neem ons mee naar je favoriete plek uit je kindertijd. Beschrijf wat je daar zag, hoorde, rook en voelde. Als je zou kunnen, welk moment zou je daar dan opnieuw beleven?",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - visuele weergave van nostalgie, emotie direct vastleggen",
  },
  {
    id: "youth-sounds",
    phase: "youth",
    phaseTitle: "Fase 2: De Vroege Jaren & Jeugd",
    title: "Het geluid van toen",
    description: "Een geluid uit je jeugd",
    question: "Welk geluid associeer je het meest met je jeugd? Vertel een korte anekdote die bij dit geluid hoort en waarom het zo belangrijk voor je is.",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - focus op zintuiglijke herinneringen",
  },
  {
    id: "youth-hero",
    phase: "youth",
    phaseTitle: "Fase 2: De Vroege Jaren & Jeugd",
    title: "Je held",
    description: "Je rolmodel uit je jeugd",
    question: "Wie was jouw grootste held of rolmodel toen je jong was, en welke invloed heeft die persoon gehad op wie je nu bent?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - reflectie op vormende invloeden",
  },

  // Fase 3: Liefde, Relaties & Vriendschappen
  {
    id: "love-connection",
    phase: "love",
    phaseTitle: "Fase 3: Liefde, Relaties & Vriendschappen",
    title: "Het moment van verbinding",
    description: "Toen je wist dat het bijzonder was",
    question: "Beschrijf het moment waarop je wist dat je verliefd was, of een heel speciale connectie voelde met iemand. Wat maakte dat gevoel zo uniek?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - klemtoon op intonatie en emotie in stem",
  },
  {
    id: "love-lessons",
    phase: "love",
    phaseTitle: "Fase 3: Liefde, Relaties & Vriendschappen",
    title: "Lessen over liefde",
    description: "Wijsheid die je wilt doorgeven",
    question: "Welke drie lessen heb je geleerd over liefde of vriendschap die je zou willen doorgeven aan toekomstige generaties?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - gecondenseerde wijsheid",
  },
  {
    id: "love-symbol",
    phase: "love",
    phaseTitle: "Fase 3: Liefde, Relaties & Vriendschappen",
    title: "Een symbolisch voorwerp",
    description: "Voorwerp dat een relatie vertegenwoordigt",
    question: "Kies een voorwerp dat symbool staat voor een belangrijke relatie of vriendschap in je leven. Laat het zien en vertel het verhaal erachter.",
    mood: "gentle",
    defaultModalities: ["video"],
    mediaFocus: "Video - visuele trigger voor een persoonlijk verhaal",
  },

  // Fase 4: Werk, Carrière & Passies
  {
    id: "work-dream-job",
    phase: "work",
    phaseTitle: "Fase 4: Werk, Carrière & Passies",
    title: "Droom versus realiteit",
    description: "Je droombaan als kind",
    question: "Wat was je droombaan als kind en hoe verhoudt zich dat tot wat je uiteindelijk bent gaan doen? Wat heb je meegenomen van die kinderdroom?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - vergelijking droom en realiteit",
  },
  {
    id: "work-passion",
    phase: "work",
    phaseTitle: "Fase 4: Werk, Carrière & Passies",
    title: "Je grootste passie",
    description: "Wat boeit je het meest?",
    question: "Laat ons iets zien (een project, een hobby, een instrument, een boek) dat jouw grootste passie buiten werk vertegenwoordigt. Vertel waarom dit je zo boeit en wat het je brengt.",
    mood: "celebratory",
    defaultModalities: ["video"],
    mediaFocus: "Video - visualiseer passie en enthousiasme",
  },
  {
    id: "work-challenge",
    phase: "work",
    phaseTitle: "Fase 4: Werk, Carrière & Passies",
    title: "Een overwonnen uitdaging",
    description: "Een professionele mijlpaal",
    question: "Beschrijf een moment waarop je een grote professionele uitdaging hebt overwonnen. Wat was die uitdaging en welke impact had het op je?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - stemgebruik voor spanning en triomf",
  },

  // Fase 5: Levenslessen & Toekomstdromen
  {
    id: "future-message",
    phase: "future",
    phaseTitle: "Fase 5: Levenslessen & Toekomstdromen",
    title: "Een boodschap voor later",
    description: "Wat wil je meegeven?",
    question: "Als je één boodschap of levensles zou mogen meegeven aan jezelf van 20 jaar geleden, of aan je nakomelingen, wat zou dat dan zijn en waarom?",
    mood: "reflective",
    defaultModalities: ["video"],
    mediaFocus: "Video - directe, persoonlijke boodschap met oogcontact",
  },
  {
    id: "future-dream",
    phase: "future",
    phaseTitle: "Fase 5: Levenslessen & Toekomstdromen",
    title: "Een onvervulde droom",
    description: "Wat koester je nog steeds?",
    question: "Welke droom of aspiratie koester je nog steeds, ongeacht leeftijd of omstandigheden? Wat maakt deze droom zo krachtig voor je?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - vastleggen van onvervulde verlangens of blijvende hoop",
  },
  {
    id: "future-gratitude",
    phase: "future",
    phaseTitle: "Fase 5: Levenslessen & Toekomstdromen",
    title: "Dankbaarheid",
    description: "Waar ben je dankbaar voor?",
    question: "Beschrijf drie dingen waar je het meest dankbaar voor bent in je leven. Waarom zijn deze zo belangrijk voor je?",
    mood: "gentle",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - focus op dankbaarheid en positieve afsluiting",
  },

  // Bonus: Aanvullende Vragen (Vrije Keuze)
  {
    id: "bonus-funny",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen",
    title: "Het grappigste moment",
    description: "Het meest onverwachte",
    question: "Wat is het grappigste of meest onverwachte moment in je leven geweest?",
    mood: "playful",
    defaultModalities: ["video", "audio", "text"],
    mediaFocus: "Vrije keuze - kies de modaliteit die het beste past",
  },
  {
    id: "bonus-relive",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen",
    title: "Een dag opnieuw",
    description: "Welke dag zou je herbeleven?",
    question: "Als je één dag opnieuw zou kunnen beleven, welke dag zou dat zijn en waarom?",
    mood: "reflective",
    defaultModalities: ["video", "audio", "text"],
    mediaFocus: "Vrije keuze - kies de modaliteit die het beste past",
  },
  {
    id: "bonus-culture",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen",
    title: "Culturele invloeden",
    description: "Kunst die je vormde",
    question: "Welke culturele invloed (muziek, kunst, boeken, film) heeft jou het meest gevormd?",
    mood: "celebratory",
    defaultModalities: ["video", "audio", "text"],
    mediaFocus: "Vrije keuze - kies de modaliteit die het beste past",
  },

  // Verborgen Dimensies: Categorie 1 - Gewoonten, Rituelen en Het Dagelijks Leven
  {
    id: "deep-daily-ritual",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "Je essentiële ritueel",
    description: "Een dagelijks moment dat je niet wilt missen",
    question: "Welk alledaags ritueel (bijv. ochtendkoffie, de avondwandeling) zou je het meest missen als je het niet meer kon doen? Beschrijf de stappen en de exacte gemoedstoestand die dit ritueel je geeft.",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - nodigt uit tot gedetailleerde beschrijving van routines",
  },
  {
    id: "deep-favorite-time",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "Je favoriete uur",
    description: "Het tijdstip van de dag dat je het meest waardeert",
    question: "Neem ons mee naar je favoriete tijdstip van de dag. Waarom is dit uur zo speciaal voor jou? Welk geluid, welke lichtval of welke stilte kenmerkt dit moment?",
    mood: "gentle",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - focus op de auditieve en zintuiglijke ervaring van tijd",
  },
  {
    id: "deep-ugly-object",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "Het lelijke object",
    description: "Iets dat je niet weggooit ondanks alles",
    question: "Laat ons het 'lelijkste' object in je huis zien, dat je toch weigert weg te gooien. Waarom heeft dit object, dat niet mooi is, zo'n emotionele grip op je?",
    mood: "playful",
    defaultModalities: ["video"],
    mediaFocus: "Video - visuele weergave van het object en emotionele verhaal",
  },

  // Verborgen Dimensies: Categorie 2 - De Vreemde en Onverklaarbare Herinneringen
  {
    id: "deep-near-death",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "Bijna-doodervaring of bizar toeval",
    description: "Een moment dat alles veranderde",
    question: "Vertel over een bijna-doodervaring of een heel bizar toeval dat je hebt meegemaakt. Wat dacht je in die milliseconden, en hoe heeft het je perspectief op het leven (of het lot) beïnvloed?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - emotionele lading en intonatie zijn cruciaal",
  },
  {
    id: "deep-misconception",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "De misvatting over jou",
    description: "Wat mensen verkeerd begrijpen",
    question: "Wat is de meest hardnekkige misvatting die mensen over jou hebben, of die je over jezelf hebt gehad? Hoe heb je deze misvatting doorbroken?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - reflectie op zelfbeeld en perceptie",
  },
  {
    id: "deep-recurring-dream",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "Je terugkerende droom",
    description: "Symbolen uit je droomwereld",
    question: "Beschrijf je typische droom (of nachtmerrie). Zijn er terugkerende symbolen of thema's? Hoe relateert deze droomwereld aan je wakkere leven?",
    mood: "reflective",
    defaultModalities: ["video"],
    mediaFocus: "Video - visuele beschrijving van droombeelden",
  },

  // Verborgen Dimensies: Categorie 3 - De Relatie tot Tijd, Geld en Keuzes
  {
    id: "deep-life-chapters",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "Hoofdstukken van je leven",
    description: "Je leven als een boek",
    question: "Als je jouw leven in hoofdstukken zou verdelen (zoals een boek), wat zouden de titel van Hoofdstuk 1 (Jeugd) en de titel van het huidige hoofdstuk zijn? Leg kort de titels uit.",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - metaforische reflectie op levensfasen",
  },
  {
    id: "deep-intuition-choice",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "Intuïtie boven logica",
    description: "Een beslissing uit je buikgevoel",
    question: "Beschrijf een moment waarop je een beslissing nam, puur en alleen uit intuïtie, tegen alle logica of advies in. Wat was de uitkomst, en wat leerde je over je eigen innerlijke stem?",
    mood: "reflective",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - persoonlijke reflectie op innerlijke wijsheid",
  },
  {
    id: "deep-money-impact",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "De meest impactvolle aankoop",
    description: "Wat geld je bracht",
    question: "Kies een willekeurig bedrag (bijv. 50 euro). Wat is de meest impactvolle of onvergetelijke aankoop die je ooit met dit bedrag (of een vergelijkbaar bedrag) hebt gedaan, en waarom?",
    mood: "reflective",
    defaultModalities: ["video"],
    mediaFocus: "Video - visualiseer de impact van geld en keuzes",
  },

  // Verborgen Dimensies: Categorie 4 - Zelfreflectie en de Onbekende Toekomst
  {
    id: "deep-shadow-side",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "Je schaduwzijde",
    description: "De kant die je minder waardeert",
    question: "Als je jouw eigen 'schaduwzijde' (de minst gewaardeerde karaktertrek) in drie woorden zou moeten beschrijven, welke zouden dat zijn? Hoe ga je daar vandaag de dag mee om?",
    mood: "reflective",
    defaultModalities: ["text"],
    mediaFocus: "Tekst - eerlijke zelfreflectie",
  },
  {
    id: "deep-life-meal",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "De maaltijd van je leven",
    description: "Een gerecht dat jou samenvat",
    question: "Als je één maaltijd zou moeten kiezen die jouw leven perfect samenvat (qua ingrediënten, smaken, of bereiding), welke zou dat zijn? Beschrijf het en vertel het verhaal erachter.",
    mood: "playful",
    defaultModalities: ["audio"],
    mediaFocus: "Audio - zintuiglijke metafoor voor het leven",
  },
  {
    id: "deep-statue",
    phase: "bonus",
    phaseTitle: "Bonus: Aanvullende Vragen - De Verborgen Dimensies",
    title: "Je eigen standbeeld",
    description: "Hoe zou jouw monument eruitzien?",
    question: "Stel je voor dat je jouw eigen standbeeld mag ontwerpen. Hoe zou het eruitzien, waar zou het staan, en welke drie woorden zouden op de sokkel staan? Geef je motivatie.",
    mood: "celebratory",
    defaultModalities: ["video"],
    mediaFocus: "Video - definitie van de zelfgekozen nalatenschap",
  },
];

// Helper functions
export function getChaptersByPhase(phase: ChapterDefinition["phase"]): ChapterDefinition[] {
  return CHAPTERS.filter((ch) => ch.phase === phase);
}

export function getPhases(): Array<{ id: ChapterDefinition["phase"]; title: string; description: string }> {
  return [
    {
      id: "intro",
      title: "Fase 1: Voorbereiding & Introductie",
      description: "Laten wennen aan het concept en de verschillende media",
    },
    {
      id: "youth",
      title: "Fase 2: De Vroege Jaren & Jeugd",
      description: "De basis leggen met herinneringen uit de kindertijd",
    },
    {
      id: "love",
      title: "Fase 3: Liefde, Relaties & Vriendschappen",
      description: "Nadenken over de menselijke connecties die je hebben gevormd",
    },
    {
      id: "work",
      title: "Fase 4: Werk, Carrière & Passies",
      description: "Inzicht in professionele en persoonlijke ontwikkeling",
    },
    {
      id: "future",
      title: "Fase 5: Levenslessen & Toekomstdromen",
      description: "Afsluitende reflectie op geleerde lessen en een blik naar de toekomst",
    },
    {
      id: "bonus",
      title: "Bonus: Aanvullende Vragen",
      description: "Extra vragen voor wie verder wil gaan",
    },
  ];
}
